### ISSUE TITLE
Report of all orcid individuals affiliated with Princeton University

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/orcid-client#1]
CSV format with the following columns:
- ORCID iD
- First Name
- Last Name
- Email
- Employment Affiliation
- Department
- Title / role

This issue is essentially about replicating the functionality of pulibrary/orcid-search with a couple more fields.

**Comment by hackmastera** [comment]
Examples given:
- https://orcid.org/0000-0002-5280-9122 lists herself as a PhD student in sociology at Princeton as part of her affiliation
- (https://orcid.org/0000-0002-3599-7168) shows that he is a professor (in neuroscience)

**Comment by hackmastera** [comment]
@windcowles for employment affiliation will you want all available or just the most recent? If all, we'll need to combine them into one column to keep the associations between organization, department, and title. For example:

Option A:
```
Name, orcid, employment affiliation
Anna, xxx, Princeton University / DRDS / Developer; CHF / Library / Developer
```

Option B:
```
Name, orcid, employment organization, department, title
Anna, xxx, Princeton University, DRDS, Developer
```

I guess there's also an Option C which is like Option B but each individual has multiple row entries (one for each employment affiliation)

**Comment by windcowles** [comment]
@hackmastera - we want current Princeton employment and so I think that most recent is probably fine.

**Comment by hackmastera** [comment]
4 reports have been added to https://drive.google.com/drive/folders/1IcQ7BtTOIqtvmvJKCo2Vd7t23mqvtBic:

- Institutional (5232 results): this searches for any record with a “Princeton University” affiliation or with Princeton’s grid id or ringgold id.
- Affiliation (5230 results): this retrieves records with a “Princeton University” affiliation
- Ringgold (4205 results): this retrieves records with an affiliation to the Princeton Ringgold id.
- Grid (187 results): this retrieves records with an affiliation to the Princeton grid id.
