### ISSUE TITLE
Investigate false negative from EE run

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/orcid-client#28]
Anu Ramaswami was not found when the EE department was searched. CSV:  https://drive.google.com/drive/folders/1088VROUHRLlBhcgrEsKr1XAqXcFlau-V w

Her ORCID record indicates that is she is affiliated with Princeton University -- investigate why the record was not retrieved to discover whether there is some improvement that we can make to the search logic.

**Comment by kmcelwee** [comment]
Running the `search_people` rake task (as of ~5pm on June 15), it seemed to work 🤷‍♂️The report that was generated contained Anu's ORCiD (0000-0002-0476-2315).  Is there another example of someone missing? Did I misunderstand something?

**Comment by kmcelwee** [comment]
@neggink If there are other examples of someone missing, feel free to add them here!
